nelmio_api_doc:
    documentation:
        info:
            title: Crypto asset evaluator
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc
