version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - php
    volumes:
      - ./:/data
    networks:
      default:
        aliases:
          - dev.local
        ipv4_address: 172.20.120.2

  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    networks:
      - default
    volumes:
      - ./:/data

  mariadb:
    image: mariadb:11-jammy
    restart: always
    userns_mode: "host"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - TZ=Europe/Vilnius
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8088:80'
    environment:
      PMA_HOST: mariadb
      PMA_DATABASE: test
      PMA_USER: test
      PMA_PASSWORD: test
      PMA_ROOT_PASSWORD: root
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      default:
        aliases:
          - dev.pma.local
        ipv4_address: 172.20.120.3

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    command: [ "rabbitmq-server" ]
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:rw
    environment:
      RABBITMQ_ERLANG_COOKIE: cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      default:
        aliases:
          - dev.rabbitmq.local
        ipv4_address: 172.20.131.4

volumes:
  mariadb-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  default:
    name: symfony
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16