version: "3.7"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    depends_on:
      - php
    volumes:
      - ./:/var/www/html/
    networks:
      default:
        aliases:
          - 'symfony.local'
        ipv4_address: 172.20.120.2

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - default
    volumes:
      - ./data/:/var/www/html/

  mariadb:
    image: mariadb:11-jammy
    restart: always
    userns_mode: "host"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    command: [ "rabbitmq-server" ]
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq:rw
    environment:
      RABBITMQ_ERLANG_COOKIE: cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      default:
        aliases:
          - 'symfony.rabbitmq.local'
        ipv4_address: 172.20.131.4

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8088:80'
    environment:
      PMA_HOST: mariadb
      PMA_DATABASE: local
      PMA_USER: local
      PMA_PASSWORD: local
      PMA_ROOT_PASSWORD: root
    links:
      - mariadb
    depends_on:
      - mariadb
    networks:
      default:
        aliases:
          - 'symfony.pma.local'
        ipv4_address: 172.20.120.3

volumes:
  mariadb-data:
    driver: local
  rabbitmq-data:
    driver: local

networks:
  default:
    name: symfony
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16